import { NextResponse } from "next/server";
import { getProviderAndKey, generateFastResponse, generateAiResponse, formatAiError } from "@/lib/ai-client";
import { getCarePlanSystemPrompt } from "@/lib/care-plan-prompts";
import { getDb } from "@/lib/db";

type Row = Record<string, unknown>;

export async function POST(request: Request) {
  const startTime = Date.now();
  const { key } = getProviderAndKey(request);
  const body = await request.json();
  const { patient_id, plan_type, phase } = body as { patient_id: string; plan_type: "current" | "discharge"; phase: "fast" | "detailed" };

  if (!patient_id || !key) {
    return NextResponse.json({ success: false, data: null, error: { code: "INVALID_INPUT", message: "Missing fields" }, meta: {} }, { status: 400 });
  }

  const db = getDb();
  const patient = db.prepare("SELECT * FROM patients WHERE id = ?").get(patient_id) as Row | undefined;
  if (!patient) return NextResponse.json({ success: false, data: null, error: { code: "NOT_FOUND", message: "Patient not found" }, meta: {} }, { status: 404 });

  const admission = db.prepare("SELECT * FROM admissions WHERE patient_id = ? AND status = 'admitted'").get(patient_id) as Row | undefined;
  const meds = db.prepare("SELECT pm.*, d.name as drug_name, d.drug_class FROM patient_medications pm JOIN drugs d ON d.id = pm.drug_id WHERE pm.patient_id = ? AND pm.status = 'active'").all(patient_id) as Row[];
  const conditions = db.prepare("SELECT c.name, c.category, pc.severity FROM patient_conditions pc JOIN conditions c ON c.id = pc.condition_id WHERE pc.patient_id = ?").all(patient_id) as Row[];
  const allergies = db.prepare("SELECT allergen, reaction, severity FROM allergies WHERE patient_id = ?").all(patient_id) as Row[];
  const vitals = db.prepare("SELECT * FROM vital_signs WHERE patient_id = ? ORDER BY recorded_at DESC LIMIT 3").all(patient_id) as Row[];
  const labs = db.prepare("SELECT test_name, value, unit, status FROM lab_results WHERE patient_id = ? ORDER BY resulted_at DESC LIMIT 8").all(patient_id) as Row[];

  const context = `PATIENT: ${patient.name}, ${patient.age}y ${patient.sex}, Blood: ${patient.blood_group}
ADMISSION: ${admission?.admission_date ?? "N/A"} | Dx: ${admission?.diagnosis ?? "N/A"} | Reason: ${admission?.reason ?? "N/A"}
ALLERGIES: ${allergies.length > 0 ? allergies.map((a) => `${a.allergen} (${a.severity})`).join(", ") : "NKDA"}
CONDITIONS: ${conditions.map((c) => `${c.name} (${c.severity})`).join(", ") || "None"}
MEDICATIONS: ${meds.map((m) => `${m.drug_name} ${m.dose} ${m.frequency}`).join(", ") || "None"}
VITALS: ${vitals.length > 0 ? `HR:${vitals[0].heart_rate} BP:${vitals[0].blood_pressure_sys}/${vitals[0].blood_pressure_dia} SpO2:${vitals[0].spo2}% Sugar:${vitals[0].blood_sugar} Pain:${vitals[0].pain_level}/10` : "None"}
LABS: ${labs.map((l) => `${l.test_name}: ${l.value} [${l.status}]`).join(", ") || "None"}`;

  // ── FAST PHASE: Llama 3.1 8B ──
  if (phase === "fast") {
    const fastPrompt = `You are a clinical AI assistant. Give a BRIEF quick assessment (5-8 bullet points) for this patient's ${plan_type === "discharge" ? "discharge readiness" : "current status"}. Reference actual vitals and medications. Be concise and specific. Use **bold** for key values. End with: "Detailed ${plan_type} plan is being generated by our advanced AI model..."`;

    try {
      const result = await generateFastResponse(key, fastPrompt, context);
      return NextResponse.json({
        success: true,
        data: { plan: result, ai_model: "Llama 3.1 8B (Fast)", plan_type, phase: "fast" },
        error: null, meta: { ai_powered: true, query_time_ms: Date.now() - startTime },
      });
    } catch (error) {
      return NextResponse.json({
        success: true,
        data: { plan: `Quick assessment unavailable: ${formatAiError(error)}. Detailed report is still generating...`, ai_model: "error", plan_type, phase: "fast" },
        error: null, meta: { ai_powered: false, query_time_ms: Date.now() - startTime },
      });
    }
  }

  // ── DETAILED PHASE: Nemotron Super 49B ──
  if (phase === "detailed") {
    const fullVitals = db.prepare("SELECT * FROM vital_signs WHERE patient_id = ? ORDER BY recorded_at DESC LIMIT 5").all(patient_id) as Row[];
    const fullLabs = db.prepare("SELECT test_name, value, unit, reference_low, reference_high, status FROM lab_results WHERE patient_id = ? ORDER BY resulted_at DESC LIMIT 15").all(patient_id) as Row[];
    const genotypes = db.prepare("SELECT gv.gene, gv.variant, gv.type FROM patient_genotypes pg JOIN gene_variants gv ON gv.id = pg.gene_variant_id WHERE pg.patient_id = ?").all(patient_id) as Row[];
    const notes = db.prepare("SELECT author, note_type, content, created_at FROM nurse_notes WHERE patient_id = ? ORDER BY created_at DESC LIMIT 5").all(patient_id) as Row[];

    const fullContext = `
PATIENT: ${patient.name}, ${patient.age}y ${patient.sex}, Blood: ${patient.blood_group}
ADMISSION: ${admission?.admission_date ?? "N/A"} | Reason: ${admission?.reason ?? "N/A"} | Dx: ${admission?.diagnosis ?? "N/A"}
ALLERGIES: ${allergies.length > 0 ? allergies.map((a) => `${a.allergen}: ${a.reaction} (${a.severity})`).join(", ") : "NKDA"}
CONDITIONS: ${conditions.map((c) => `${c.name} (${c.category}) — ${c.severity}`).join(", ") || "None"}
GENETICS: ${genotypes.length > 0 ? genotypes.map((g) => `${g.gene} ${g.variant}: ${String(g.type).replace("_", " ")}`).join(", ") : "No genetic testing"}
MEDICATIONS (${meds.length}): ${meds.map((m) => `${m.drug_name} ${m.dose} — ${m.frequency} via ${m.route} (${m.drug_class})`).join("; ") || "None"}
VITALS: ${fullVitals.map((v) => `[${v.recorded_at}] HR:${v.heart_rate} BP:${v.blood_pressure_sys}/${v.blood_pressure_dia} SpO2:${v.spo2}% Sugar:${v.blood_sugar} Temp:${v.temperature}°F Pain:${v.pain_level}/10`).join(" | ") || "None"}
LABS: ${fullLabs.map((l) => `${l.test_name}: ${l.value} ${l.unit} (${l.reference_low}-${l.reference_high}) [${String(l.status).toUpperCase()}]`).join("; ") || "None"}
NOTES: ${notes.map((n) => `[${n.created_at}] ${n.author}: ${n.content}`).join("; ") || "None"}`;

    const systemPrompt = getCarePlanSystemPrompt(plan_type);
    try {
      const plan = await generateAiResponse(key, systemPrompt,
        `IMPORTANT: Generate a detailed ${plan_type === "discharge" ? "DISCHARGE" : "CURRENT"} care plan. Use ACTUAL patient data.\n\n${fullContext}`
      );
      return NextResponse.json({
        success: true,
        data: { plan, ai_model: "Nemotron Super 49B (Detailed)", plan_type, phase: "detailed" },
        error: null, meta: { ai_powered: true, query_time_ms: Date.now() - startTime },
      });
    } catch (error) {
      return NextResponse.json({
        success: true,
        data: { plan: `Detailed plan generation failed: ${formatAiError(error)}`, ai_model: "error", plan_type, phase: "detailed" },
        error: null, meta: { ai_powered: false, query_time_ms: Date.now() - startTime },
      });
    }
  }

  return NextResponse.json({ success: false, data: null, error: { code: "INVALID_PHASE", message: "phase must be 'fast' or 'detailed'" }, meta: {} }, { status: 400 });
}
